import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const osans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-osans",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${osans.variable}`}>
      <body className="font-osans bg-backg px-3">
        <Header />
        {children}
      </body>
    </html>
  );
}
