import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/components";
import { Alkatra } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const alkatra = Alkatra({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-alkatra",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${alkatra.variable}`}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
